const SECURITY_EVENTS = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",

    INVALID_JWT: "INVALID_JWT",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",

    ACCESS_DENIED: "ACCESS_DENIED",

    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

    IP_BLOCKED: "IP_BLOCKED",

    API_ACCESS: "API_ACCESS"
};

module.exports = SECURITY_EVENTS;